Veldris_Lab_MapScripts::
	.byte 0

Veldris_Lab_EventScript_StarterBall1::
	msgbox Veldris_Lab_Text_StarterBallPlaceholder, MSGBOX_NPC
	end

Veldris_Lab_EventScript_StarterBall2::
	msgbox Veldris_Lab_Text_StarterBallPlaceholder, MSGBOX_NPC
	end

Veldris_Lab_EventScript_StarterBall3::
	msgbox Veldris_Lab_Text_StarterBallPlaceholder, MSGBOX_NPC
	end

Veldris_Lab_Text_StarterBallPlaceholder:
	.string "A starter Poke Ball sits here.$"
