"""Import spilledpizza's Diamond/Pearl sprite set from Team-Aquas-Asset-Repo (author asked 2026-10-10: the whole set).

What it does (re-runnable; every generated block sits between VELDRIS-DP markers and is replaced on each run):
  * 70 NPC overworlds (16x32, 9 frames)  -> graphics/object_events/pics/people/dp/<name>.png
      OBJ_EVENT_GFX_DP_<NAME>, each with its own palette (taken from the PNG), tag 0x1170 + n
  * 93 trainer front pics (64x64)        -> graphics/trainers/front_pics/dp/<name>.png
      TRAINER_PIC_DP_<NAME>; in trainers.party write  Pic: DP <Name With Spaces>
  * Lucas and Dawn player sheets and back pics are copied to graphics/.../dp/ for the outfit system
    (design/player-customization.md), not registered here.

Palettes are padded to 16 colours (some source pics have 13-15). Index 0 stays the transparent colour.
Usage (repo root):  python3 design/tools/sprites/import_dp.py [path to team-aquas-asset-repo]
"""
import re, shutil, sys
from pathlib import Path
from PIL import Image

V = Path(__file__).resolve().parents[3]
TAAR = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("/home/claude/24rousol-hub/team-aquas-asset-repo")
SRC = TAAR / "Overworld Trainer Sprites/spilledpizza/graphics"
OW_OUT = V / "graphics/object_events/pics/people/dp"
FP_OUT = V / "graphics/trainers/front_pics/dp"
PLAYER_OUT = V / "graphics/object_events/pics/people/dp_player"
BACK_OUT = V / "graphics/trainers/back_pics/dp"
TAG_BASE = 0x1170
SKIP_FRONT = {"DP_cynthia_mugshot"}           # a cut-in portrait, not a battle pic

def padded_copy(src, dst):
    """Copy an indexed PNG, padding its palette to 16 entries (black)."""
    im = Image.open(src)
    assert im.mode == "P", src
    pal = im.getpalette()[: 16 * 3]
    pal += [0, 0, 0] * (16 - len(pal) // 3)
    im.putpalette(pal)
    dst.parent.mkdir(parents=True, exist_ok=True)
    im.save(dst)

def upper(stem):                             # DP_rich_boy -> RICH_BOY
    return re.sub(r"[^A-Z0-9]+", "_", stem[3:].upper()).strip("_")
def camel(stem):                             # DP_rich_boy -> RichBoy
    return "".join(p.capitalize() for p in re.split(r"[^A-Za-z0-9]+", stem[3:]) if p)

def replace_block(path, anchor_re, block, before=True):
    """Put block between // VELDRIS-DP markers. If markers exist, replace; else insert at the anchor line."""
    p = V / path; s = p.read_text()
    tag = f"VELDRIS-DP {block[0]}"
    begin, end = f"// {tag} BEGIN (design/tools/sprites/import_dp.py)\n", f"// {tag} END\n"
    body = begin + "".join(block[1]) + end
    m = re.search(re.escape(begin) + r".*?" + re.escape(end), s, re.S)
    if m:
        s = s[:m.start()] + body + s[m.end():]
    else:
        a = re.search(anchor_re, s, re.M)
        assert a, (path, anchor_re)
        i = a.start() if before else a.end()
        s = s[:i] + body + s[i:]
    p.write_text(s)

# ---------- overworlds
ow = sorted(f for f in (SRC / "object_events/pics/people").glob("DP_*.png"))
for d in (OW_OUT, FP_OUT):
    if d.exists(): shutil.rmtree(d)
ow_rows = []
for n, f in enumerate(ow):
    im = Image.open(f); assert im.size == (144, 32), f
    name = f.stem[3:].lower()
    padded_copy(f, OW_OUT / f"{name}.png")
    ow_rows.append((upper(f.stem), camel(f.stem), name, TAG_BASE + n))

# player sheets and back pics (used by the outfit system)
for who in ("lucas", "dawn"):
    for f in sorted((SRC / f"object_events/pics/people/{who}").glob("*.png")):
        padded_copy(f, PLAYER_OUT / who / f.name)
    padded_copy(SRC / f"trainers/back_pics/{who}.png", BACK_OUT / f"{who}.png")

data = ["// Diamond/Pearl overworlds by spilledpizza and others (CREDITS.md). Generated by design/tools/sprites/import_dp.py.\n",
        "// Each has its own palette, so keep the number of different DP people on one screen modest.\n\n"]
for U, C, name, tag in ow_rows:
    data.append(f'const u32 gObjectEventPic_DP_{C}[] = INCGFX_U32("graphics/object_events/pics/people/dp/{name}.png", ".4bpp", "-mwidth 2 -mheight 4");\n')
    data.append(f'const u16 gObjectEventPal_DP_{C}[] = INCGFX_U16("graphics/object_events/pics/people/dp/{name}.png", ".gbapal");\n')
data.append("\n")
for U, C, name, tag in ow_rows:
    data.append(f"static const struct SpriteFrameImage sPicTable_DP_{C}[] = {{\n    overworld_ascending_frames(gObjectEventPic_DP_{C}, 2, 4),\n}};\n\n")
for U, C, name, tag in ow_rows:
    data.append(f"""const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_{C} = {{
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_{U},
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_{C},
}};

""")
(V / "src/data/object_events/veldris_dp_object_events.h").write_text("".join(data))

replace_block("include/constants/event_objects.h", r"^    NUM_OBJ_EVENT_GFX,", ("ENUM", [f"    OBJ_EVENT_GFX_DP_{U},\n" for U, *_ in ow_rows]))
replace_block("include/constants/event_objects.h", r"^#define OBJ_EVENT_PAL_TAG_NONE", ("TAGS", [f"#define OBJ_EVENT_PAL_TAG_DP_{U:<24} 0x{tag:04X}\n" for U, C, n, tag in ow_rows]))
replace_block("src/data/object_events/object_event_graphics_info_pointers.h", r"^const struct ObjectEventGraphicsInfo \*const gObjectEventGraphicsInfoPointers",
              ("EXTERNS", [f"extern const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_{C};\n" for U, C, *_ in ow_rows]))
replace_block("src/data/object_events/object_event_graphics_info_pointers.h", r"^};", ("POINTERS", [f"    [OBJ_EVENT_GFX_DP_{U}] = &gObjectEventGraphicsInfo_DP_{C},\n" for U, C, *_ in ow_rows]))
replace_block("src/event_object_movement.c", r'^#include "data/object_events/object_event_graphics_info_followers.h"\n',
              ("INCLUDE", ['#include "data/object_events/veldris_dp_object_events.h"\n']), before=False)
replace_block("src/event_object_movement.c", r"^static const struct SpritePalette sObjectEventSpritePalettes\[\] = \{\n",
              ("PALETTES", [f"    {{gObjectEventPal_DP_{C}, OBJ_EVENT_PAL_TAG_DP_{U}}},\n" for U, C, *_ in ow_rows]), before=False)

# ---------- trainer front pics
fp_rows = []
for f in sorted((SRC / "trainers/front_pics").glob("DP_*.png")):
    if f.stem in SKIP_FRONT: continue
    im = Image.open(f); assert im.size == (64, 64), f
    name = f.stem[3:].lower()
    padded_copy(f, FP_OUT / f"{name}.png")
    fp_rows.append((upper(f.stem), camel(f.stem), name))
replace_block("include/constants/trainers.h", r"^    TRAINER_PIC_COUNT,", ("PICS", [f"    TRAINER_PIC_DP_{U},\n" for U, *_ in fp_rows]))
BACK = {"LUCAS": "lucas", "DAWN": "dawn"}   # player outfit back pictures (design/player-customization.md)
picdata = [f'const u32 gTrainerFrontPic_DP_{C}[] = INCGFX_U32("graphics/trainers/front_pics/dp/{n}.png", ".4bpp.smol");\n'
           f'const u16 gTrainerPalette_DP_{C}[] = INCGFX_U16("graphics/trainers/front_pics/dp/{n}.png", ".gbapal");\n' for U, C, n in fp_rows]
picdata += [f'const u8 gTrainerBackPic_DP_{b.capitalize()}[] = INCGFX_U8("graphics/trainers/back_pics/dp/{b}.png", ".4bpp");\n'
            f'const u16 gTrainerBackPicPalette_DP_{b.capitalize()}[] = INCGFX_U16("graphics/trainers/back_pics/dp/{b}.png", ".gbapal");\n' for b in BACK.values()]
replace_block("src/data/graphics/trainers.h", r"^const struct TrainerPicInfo gTrainerPicInfo\[TRAINER_PIC_COUNT\] =", ("PICDATA", picdata))
def entry(U, C):
    e = f"    [TRAINER_PIC_DP_{U}] =\n    {{\n        .frontPic = TRAINER_FRONT_PIC(gTrainerFrontPic_DP_{C}, gTrainerPalette_DP_{C}),\n"
    if U in BACK:
        b = BACK[U].capitalize()
        e += f"        .backPic = TRAINER_BACK_PIC(4, gTrainerBackPic_DP_{b}, gTrainerBackPicPalette_DP_{b}, sBackAnims_Hoenn),\n"
    return e + "    },\n"
replace_block("src/data/graphics/trainers.h", r"^};\s*\Z", ("TABLE", [entry(U, C) for U, C, n in fp_rows]))

# list for the docs
lines = ["# DP sprites imported by design/tools/sprites/import_dp.py\n\n## Overworlds (map.json graphics_id)\n\n"]
lines += [f"- `OBJ_EVENT_GFX_DP_{U}`\n" for U, *_ in ow_rows]
lines += ["\n## Trainer pics (trainers.party `Pic:`)\n\n"]
lines += [f"- `Pic: DP {U.replace('_', ' ').title()}` (`TRAINER_PIC_DP_{U}`)\n" for U, *_ in fp_rows]
(V / "design/dp-sprite-list.md").write_text("".join(lines))
print(len(ow_rows), "overworlds,", len(fp_rows), "front pics")
