"""Colour tables for the player customization (design/player-customization.md).

Brendan's and May's palettes put the same body part at the same index on the overworld sheet, the reflection and the
battle pictures, so a recolour is a list of (index, new colour) per part. For every option this keeps the part's own
light-to-dark steps and moves them to the option's colour (hue and saturation from the key colour, lightness shifted
by the key's distance from the part's reference shade).

Writes src/data/veldris_look_palettes.h and a preview sheet (argument 1, default: scratch path printed at the end).
Run from the repo root:  python3 design/tools/sprites/player_look.py [preview.png]
"""
import colorsys, sys
from pathlib import Path
import numpy as np
from PIL import Image, ImageDraw

V = Path(__file__).resolve().parents[3]
GENDERS = ("brendan", "may")
KINDS = ("ow", "refl", "trainer")           # LOOK_KIND_* order in C
PAL = {
    "ow": "graphics/object_events/palettes/{}.pal",
    "refl": "graphics/object_events/palettes/{}_reflection.pal",
    "trainer": "graphics/trainers/palettes/{}.pal",
}
# part -> (indices light to dark, reference index) per gender
PARTS = {
    "skin":   {"brendan": ((1, 2, 3), 2), "may": ((1, 2, 3), 2)},
    "hair":   {"brendan": ((5, 6, 7, 8), 6), "may": ((7, 8), 7)},   # Brendan: his navy clothes (his hair is under the cap)
    "top":    {"brendan": ((12, 13), 12), "may": ((12, 13), 12)},
    "accent": {"brendan": ((10, 11), 10), "may": ((10, 11), 10)},
}
# option keys: None = keep the original colours. Option names live in src/veldris_look.c and must match this order.
OPTIONS = {
    "skin": [None, (255, 226, 205), (214, 160, 112), (166, 108, 74), (110, 70, 52)],   # default, pale, tan, brown, deep
    "hair": {
        "brendan": [None, (58, 58, 64), (120, 84, 60), (60, 120, 70), (150, 50, 50), (100, 70, 150), (120, 124, 132), (170, 150, 100)],
        #           navy   black         brown          green          red            purple          grey             khaki
        "may": [None, (60, 52, 60), (232, 196, 90), (206, 72, 58), (70, 110, 220), (80, 170, 90), (238, 130, 180), (214, 214, 226)],
        #       brown  black         blonde          red             blue            green          pink             silver
    },
    "top":    [None, (70, 110, 220), (80, 170, 90), (238, 200, 60), (150, 90, 200), (240, 140, 50), (70, 70, 80), (232, 232, 240)],
    #          red    blue            green          yellow          purple          orange          black         white
    "accent": [None, (220, 70, 60), (70, 110, 220), (238, 200, 60), (150, 90, 200), (240, 140, 50), (70, 70, 80), (232, 232, 240)],
    #          green  red             blue            yellow          purple          orange          black         white
}
NOPT = 8

def read_pal(rel):
    t = (V / rel).read_text().split(); n = int(t[2])
    return [tuple(int(x) for x in t[3 + 3 * i:6 + 3 * i]) for i in range(n)]

def hls(c): return colorsys.rgb_to_hls(*(v / 255 for v in c))
def rgb(h, l, s): return tuple(int(round(max(0, min(1, v)) * 255)) for v in colorsys.hls_to_rgb(h, l, s))

def recolour(colours, ref, key):
    """Move a ramp so its reference shade becomes the key colour, keeping the steps between shades."""
    hr, lr, sr = hls(ref); hk, lk, sk = hls(key)
    out = []
    for c in colours:
        h, l, s = hls(c)
        s2 = s * (sk / sr) if sr > 0.02 else sk
        out.append(rgb(hk, l + (lk - lr), min(1, s2)))
    return out

def gba(c):  # 15-bit BGR
    r, g, b = (v >> 3 for v in c); return r | (g << 5) | (b << 10)

def opt_list(part, g):
    o = OPTIONS[part]; return o[g] if isinstance(o, dict) else o

pals = {g: {k: read_pal(PAL[k].format(g)) for k in KINDS} for g in GENDERS}
table = {}   # (g, kind, part, opt) -> list of colours
for g in GENDERS:
    for part, per in PARTS.items():
        idx, ref = per[g]
        for oi in range(NOPT):
            opts = opt_list(part, g)
            key = opts[oi] if oi < len(opts) else None
            for kind in KINDS:
                P = pals[g][kind]; orig = [P[i] for i in idx]
                if key is None:
                    table[(g, kind, part, oi)] = orig
                elif kind == "refl":
                    # the reflection is the overworld colour pushed toward the water; keep each channel's ratio
                    base = pals[g]["ow"]; new = recolour([base[i] for i in idx], base[ref], key)
                    table[(g, kind, part, oi)] = [tuple(min(255, int(n * (r + 8) / (b + 8))) for n, r, b in zip(nc, P[i], base[i]))
                                                  for nc, i in zip(new, idx)]
                else:
                    table[(g, kind, part, oi)] = recolour(orig, P[ref], key)

# ---- C header
L = ["// Generated by design/tools/sprites/player_look.py. Do not edit by hand.\n",
     "// sLookIndices[gender][part] = palette indices (0 = unused); sLookColours[gender][kind][part][option][n] = new colour.\n\n",
     "static const u8 sLookIndices[GENDER_COUNT][LOOK_PART_COUNT][LOOK_MAX_SHADES] = {\n"]
for g in GENDERS:
    L.append("    {")
    L.append(", ".join("{" + ", ".join(str(i) for i in (list(PARTS[p][g][0]) + [0, 0, 0, 0])[:4]) + "}" for p in PARTS))
    L.append("},\n")
L.append("};\n\nstatic const u16 sLookColours[GENDER_COUNT][LOOK_KIND_COUNT][LOOK_PART_COUNT][LOOK_OPTIONS][LOOK_MAX_SHADES] = {\n")
for g in GENDERS:
    L.append(f"    // {g}\n    {{\n")
    for kind in KINDS:
        L.append(f"        {{ // {kind}\n")
        for part in PARTS:
            rows = []
            for oi in range(NOPT):
                cs = table[(g, kind, part, oi)] + [(0, 0, 0)] * 4
                rows.append("{" + ", ".join(f"0x{gba(c):04X}" for c in cs[:4]) + "}")
            L.append(f"            {{{', '.join(rows)}}}, // {part}\n")
        L.append("        },\n")
    L.append("    },\n")
L.append("};\n")
(V / "src/data/veldris_look_palettes.h").write_text("".join(L))

# ---- preview: every option of every part, on the overworld frame and the front picture
def apply(img_path, palette, recol, frame=None):
    im = Image.open(V / img_path); a = np.array(im)
    if frame: a = a[frame[1]:frame[3], frame[0]:frame[2]]
    P = np.array(palette[:16] + [(0, 0, 0)] * (16 - len(palette)), dtype=np.uint8).copy()
    for i, c in recol.items(): P[i] = c
    out = P[a]; out[a == 0] = (236, 238, 242)
    return Image.fromarray(out)

rows = []
for g in GENDERS:
    for part in PARTS:
        idx, _ = PARTS[part][g]
        n = len(opt_list(part, g))
        tiles = []
        for oi in range(n):
            ow = apply(f"graphics/object_events/pics/people/{g}/walking.png", pals[g]["ow"],
                       dict(zip(idx, table[(g, 'ow', part, oi)])), (0, 0, 16, 32)).resize((32, 64), Image.NEAREST)
            fr = apply(f"graphics/trainers/front_pics/{g}.png", pals[g]["trainer"], dict(zip(idx, table[(g, 'trainer', part, oi)])),
                       (0, 0, 64, 64))
            t = Image.new("RGB", (100, 70), (236, 238, 242)); t.paste(ow, (2, 3)); t.paste(fr, (36, 3)); tiles.append(t)
        row = Image.new("RGB", (110 + 100 * NOPT, 74), (255, 255, 255)); d = ImageDraw.Draw(row)
        d.text((4, 30), f"{g} {part}", fill=(0, 0, 0))
        for i, t in enumerate(tiles): row.paste(t, (110 + i * 100, 2))
        rows.append(row)
sheet = Image.new("RGB", (rows[0].width, 74 * len(rows)), (255, 255, 255))
for i, r in enumerate(rows): sheet.paste(r, (0, i * 74))
out = Path(sys.argv[1]) if len(sys.argv) > 1 else V / "build/look_preview.png"
out.parent.mkdir(parents=True, exist_ok=True); sheet.save(out); print("wrote", out)
