gText_Birch_Welcome::
	.string "Ah, there you are! Sorry to keep\n"
	.string "you waiting.\p"
	.string "Welcome to VELDRIS, and to the\n"
	.string "world of POKéMON!\p"
	.string "My name is FENNICK.\p"
	.string "Everyone calls me the POKéMON\n"
	.string "PROFESSOR. Except my ZIGZAGOON.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This land is home to creatures\n"
	.string "known as POKéMON.\p"
	.string "People here live alongside them.\n"
	.string "They plough the fields together,\l"
	.string "and now and then, battle each other.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel a few of them,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "So you're {PLAYER}{KUN}. Splendid.\n"
	.string "I'll remember that. Probably.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and go out into\n"
	.string "VELDRIS, where dreams, adventure,\l"
	.string "and friendships await!\p"
	.string "Oh, and should you meet a boy\n"
	.string "named BEAUREGARD GOLDSWORTH IV,\l"
	.string "do try to be polite.\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
