// Player outfit sprite sets (design/player-customization.md). Generated by design/tools/sprites/player_outfits.py.

const u32 gObjectEventPic_VeldrisRSMWalking[] = INCGFX_U32("graphics/object_events/pics/people/ruby_sapphire_brendan/walking.png", ".4bpp", "-mwidth 2 -mheight 4");

const u32 gObjectEventPic_VeldrisRSMRunning[] = INCGFX_U32("graphics/object_events/pics/people/ruby_sapphire_brendan/running.png", ".4bpp", "-mwidth 2 -mheight 4");

static const struct SpriteFrameImage sPicTable_VeldrisRSMNormal[] = {
    overworld_frame(gObjectEventPic_VeldrisRSMWalking, 2, 4, 0),
    overworld_frame(gObjectEventPic_VeldrisRSMWalking, 2, 4, 1),
    overworld_frame(gObjectEventPic_VeldrisRSMWalking, 2, 4, 2),
    overworld_frame(gObjectEventPic_VeldrisRSMWalking, 2, 4, 3),
    overworld_frame(gObjectEventPic_VeldrisRSMWalking, 2, 4, 4),
    overworld_frame(gObjectEventPic_VeldrisRSMWalking, 2, 4, 5),
    overworld_frame(gObjectEventPic_VeldrisRSMWalking, 2, 4, 6),
    overworld_frame(gObjectEventPic_VeldrisRSMWalking, 2, 4, 7),
    overworld_frame(gObjectEventPic_VeldrisRSMWalking, 2, 4, 8),
    overworld_frame(gObjectEventPic_VeldrisRSMRunning, 2, 4, 0),
    overworld_frame(gObjectEventPic_VeldrisRSMRunning, 2, 4, 1),
    overworld_frame(gObjectEventPic_VeldrisRSMRunning, 2, 4, 2),
    overworld_frame(gObjectEventPic_VeldrisRSMRunning, 2, 4, 3),
    overworld_frame(gObjectEventPic_VeldrisRSMRunning, 2, 4, 4),
    overworld_frame(gObjectEventPic_VeldrisRSMRunning, 2, 4, 5),
    overworld_frame(gObjectEventPic_VeldrisRSMRunning, 2, 4, 6),
    overworld_frame(gObjectEventPic_VeldrisRSMRunning, 2, 4, 7),
    overworld_frame(gObjectEventPic_VeldrisRSMRunning, 2, 4, 8),
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_VeldrisRSMNormal = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_RS_BRENDAN,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_BRIDGE_REFLECTION,
    .size = 512,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_PLAYER,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_BrendanMayNormal,
    .images = sPicTable_VeldrisRSMNormal,
};

const u32 gObjectEventPic_VeldrisRSFWalking[] = INCGFX_U32("graphics/object_events/pics/people/ruby_sapphire_may/walking.png", ".4bpp", "-mwidth 2 -mheight 4");

const u32 gObjectEventPic_VeldrisRSFRunning[] = INCGFX_U32("graphics/object_events/pics/people/ruby_sapphire_may/running.png", ".4bpp", "-mwidth 2 -mheight 4");

static const struct SpriteFrameImage sPicTable_VeldrisRSFNormal[] = {
    overworld_frame(gObjectEventPic_VeldrisRSFWalking, 2, 4, 0),
    overworld_frame(gObjectEventPic_VeldrisRSFWalking, 2, 4, 1),
    overworld_frame(gObjectEventPic_VeldrisRSFWalking, 2, 4, 2),
    overworld_frame(gObjectEventPic_VeldrisRSFWalking, 2, 4, 3),
    overworld_frame(gObjectEventPic_VeldrisRSFWalking, 2, 4, 4),
    overworld_frame(gObjectEventPic_VeldrisRSFWalking, 2, 4, 5),
    overworld_frame(gObjectEventPic_VeldrisRSFWalking, 2, 4, 6),
    overworld_frame(gObjectEventPic_VeldrisRSFWalking, 2, 4, 7),
    overworld_frame(gObjectEventPic_VeldrisRSFWalking, 2, 4, 8),
    overworld_frame(gObjectEventPic_VeldrisRSFRunning, 2, 4, 0),
    overworld_frame(gObjectEventPic_VeldrisRSFRunning, 2, 4, 1),
    overworld_frame(gObjectEventPic_VeldrisRSFRunning, 2, 4, 2),
    overworld_frame(gObjectEventPic_VeldrisRSFRunning, 2, 4, 3),
    overworld_frame(gObjectEventPic_VeldrisRSFRunning, 2, 4, 4),
    overworld_frame(gObjectEventPic_VeldrisRSFRunning, 2, 4, 5),
    overworld_frame(gObjectEventPic_VeldrisRSFRunning, 2, 4, 6),
    overworld_frame(gObjectEventPic_VeldrisRSFRunning, 2, 4, 7),
    overworld_frame(gObjectEventPic_VeldrisRSFRunning, 2, 4, 8),
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_VeldrisRSFNormal = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_RS_MAY,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_BRIDGE_REFLECTION,
    .size = 512,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_PLAYER,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_BrendanMayNormal,
    .images = sPicTable_VeldrisRSFNormal,
};

const u16 gObjectEventPal_VeldrisDPM[] = INCGFX_U16("graphics/object_events/pics/people/dp_player/lucas/walking.png", ".gbapal");

const u32 gObjectEventPic_VeldrisDPMWalking[] = INCGFX_U32("graphics/object_events/pics/people/dp_player/lucas/walking.png", ".4bpp", "-mwidth 2 -mheight 4");

const u32 gObjectEventPic_VeldrisDPMRunning[] = INCGFX_U32("graphics/object_events/pics/people/dp_player/lucas/running.png", ".4bpp", "-mwidth 2 -mheight 4");

static const struct SpriteFrameImage sPicTable_VeldrisDPMNormal[] = {
    overworld_frame(gObjectEventPic_VeldrisDPMWalking, 2, 4, 0),
    overworld_frame(gObjectEventPic_VeldrisDPMWalking, 2, 4, 1),
    overworld_frame(gObjectEventPic_VeldrisDPMWalking, 2, 4, 2),
    overworld_frame(gObjectEventPic_VeldrisDPMWalking, 2, 4, 3),
    overworld_frame(gObjectEventPic_VeldrisDPMWalking, 2, 4, 4),
    overworld_frame(gObjectEventPic_VeldrisDPMWalking, 2, 4, 5),
    overworld_frame(gObjectEventPic_VeldrisDPMWalking, 2, 4, 6),
    overworld_frame(gObjectEventPic_VeldrisDPMWalking, 2, 4, 7),
    overworld_frame(gObjectEventPic_VeldrisDPMWalking, 2, 4, 8),
    overworld_frame(gObjectEventPic_VeldrisDPMRunning, 2, 4, 0),
    overworld_frame(gObjectEventPic_VeldrisDPMRunning, 2, 4, 1),
    overworld_frame(gObjectEventPic_VeldrisDPMRunning, 2, 4, 2),
    overworld_frame(gObjectEventPic_VeldrisDPMRunning, 2, 4, 3),
    overworld_frame(gObjectEventPic_VeldrisDPMRunning, 2, 4, 4),
    overworld_frame(gObjectEventPic_VeldrisDPMRunning, 2, 4, 5),
    overworld_frame(gObjectEventPic_VeldrisDPMRunning, 2, 4, 6),
    overworld_frame(gObjectEventPic_VeldrisDPMRunning, 2, 4, 7),
    overworld_frame(gObjectEventPic_VeldrisDPMRunning, 2, 4, 8),
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_VeldrisDPMNormal = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_VELDRIS_DP_M,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_BRIDGE_REFLECTION,
    .size = 512,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_PLAYER,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_BrendanMayNormal,
    .images = sPicTable_VeldrisDPMNormal,
};

const u32 gObjectEventPic_VeldrisDPMMachBike[] = INCGFX_U32("graphics/object_events/pics/people/dp_player/lucas/mach_bike.png", ".4bpp", "-mwidth 4 -mheight 4");

static const struct SpriteFrameImage sPicTable_VeldrisDPMMachBike[] = {
    overworld_ascending_frames(gObjectEventPic_VeldrisDPMMachBike, 4, 4),
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_VeldrisDPMMachBike = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_VELDRIS_DP_M,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_BRIDGE_REFLECTION,
    .size = 512,
    .width = 32,
    .height = 32,
    .paletteSlot = PALSLOT_PLAYER,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_BIKE_TIRE,
    .oam = &gObjectEventBaseOam_32x32,
    .subspriteTables = sOamTables_32x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_VeldrisDPMMachBike,
};

const u32 gObjectEventPic_VeldrisDPMSurfing[] = INCGFX_U32("graphics/object_events/pics/people/dp_player/lucas/surfing.png", ".4bpp", "-mwidth 4 -mheight 4");

static const struct SpriteFrameImage sPicTable_VeldrisDPMSurfing[] = {
    overworld_frame(gObjectEventPic_VeldrisDPMSurfing, 4, 4, 0),
    overworld_frame(gObjectEventPic_VeldrisDPMSurfing, 4, 4, 2),
    overworld_frame(gObjectEventPic_VeldrisDPMSurfing, 4, 4, 4),
    overworld_frame(gObjectEventPic_VeldrisDPMSurfing, 4, 4, 0),
    overworld_frame(gObjectEventPic_VeldrisDPMSurfing, 4, 4, 0),
    overworld_frame(gObjectEventPic_VeldrisDPMSurfing, 4, 4, 2),
    overworld_frame(gObjectEventPic_VeldrisDPMSurfing, 4, 4, 2),
    overworld_frame(gObjectEventPic_VeldrisDPMSurfing, 4, 4, 4),
    overworld_frame(gObjectEventPic_VeldrisDPMSurfing, 4, 4, 4),
    overworld_frame(gObjectEventPic_VeldrisDPMSurfing, 4, 4, 1),
    overworld_frame(gObjectEventPic_VeldrisDPMSurfing, 4, 4, 3),
    overworld_frame(gObjectEventPic_VeldrisDPMSurfing, 4, 4, 5),
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_VeldrisDPMSurfing = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_VELDRIS_DP_M,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 512,
    .width = 32,
    .height = 32,
    .paletteSlot = PALSLOT_PLAYER,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_32x32,
    .subspriteTables = sOamTables_32x32,
    .anims = sAnimTable_Surfing,
    .images = sPicTable_VeldrisDPMSurfing,
};

const u32 gObjectEventPic_VeldrisDPMFishing[] = INCGFX_U32("graphics/object_events/pics/people/dp_player/lucas/fishing.png", ".4bpp", "-mwidth 4 -mheight 4");

static const struct SpriteFrameImage sPicTable_VeldrisDPMFishing[] = {
    overworld_ascending_frames(gObjectEventPic_VeldrisDPMFishing, 4, 4),
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_VeldrisDPMFishing = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_VELDRIS_DP_M,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_BRIDGE_REFLECTION,
    .size = 512,
    .width = 32,
    .height = 32,
    .paletteSlot = PALSLOT_PLAYER,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_32x32,
    .subspriteTables = sOamTables_32x32,
    .anims = sAnimTable_Fishing,
    .images = sPicTable_VeldrisDPMFishing,
};

const u16 gObjectEventPal_VeldrisDPF[] = INCGFX_U16("graphics/object_events/pics/people/dp_player/dawn/walking.png", ".gbapal");

const u32 gObjectEventPic_VeldrisDPFWalking[] = INCGFX_U32("graphics/object_events/pics/people/dp_player/dawn/walking.png", ".4bpp", "-mwidth 2 -mheight 4");

const u32 gObjectEventPic_VeldrisDPFRunning[] = INCGFX_U32("graphics/object_events/pics/people/dp_player/dawn/running.png", ".4bpp", "-mwidth 2 -mheight 4");

static const struct SpriteFrameImage sPicTable_VeldrisDPFNormal[] = {
    overworld_frame(gObjectEventPic_VeldrisDPFWalking, 2, 4, 0),
    overworld_frame(gObjectEventPic_VeldrisDPFWalking, 2, 4, 1),
    overworld_frame(gObjectEventPic_VeldrisDPFWalking, 2, 4, 2),
    overworld_frame(gObjectEventPic_VeldrisDPFWalking, 2, 4, 3),
    overworld_frame(gObjectEventPic_VeldrisDPFWalking, 2, 4, 4),
    overworld_frame(gObjectEventPic_VeldrisDPFWalking, 2, 4, 5),
    overworld_frame(gObjectEventPic_VeldrisDPFWalking, 2, 4, 6),
    overworld_frame(gObjectEventPic_VeldrisDPFWalking, 2, 4, 7),
    overworld_frame(gObjectEventPic_VeldrisDPFWalking, 2, 4, 8),
    overworld_frame(gObjectEventPic_VeldrisDPFRunning, 2, 4, 0),
    overworld_frame(gObjectEventPic_VeldrisDPFRunning, 2, 4, 1),
    overworld_frame(gObjectEventPic_VeldrisDPFRunning, 2, 4, 2),
    overworld_frame(gObjectEventPic_VeldrisDPFRunning, 2, 4, 3),
    overworld_frame(gObjectEventPic_VeldrisDPFRunning, 2, 4, 4),
    overworld_frame(gObjectEventPic_VeldrisDPFRunning, 2, 4, 5),
    overworld_frame(gObjectEventPic_VeldrisDPFRunning, 2, 4, 6),
    overworld_frame(gObjectEventPic_VeldrisDPFRunning, 2, 4, 7),
    overworld_frame(gObjectEventPic_VeldrisDPFRunning, 2, 4, 8),
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_VeldrisDPFNormal = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_VELDRIS_DP_F,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_BRIDGE_REFLECTION,
    .size = 512,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_PLAYER,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_BrendanMayNormal,
    .images = sPicTable_VeldrisDPFNormal,
};

const u32 gObjectEventPic_VeldrisDPFMachBike[] = INCGFX_U32("graphics/object_events/pics/people/dp_player/dawn/mach_bike.png", ".4bpp", "-mwidth 4 -mheight 4");

static const struct SpriteFrameImage sPicTable_VeldrisDPFMachBike[] = {
    overworld_ascending_frames(gObjectEventPic_VeldrisDPFMachBike, 4, 4),
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_VeldrisDPFMachBike = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_VELDRIS_DP_F,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_BRIDGE_REFLECTION,
    .size = 512,
    .width = 32,
    .height = 32,
    .paletteSlot = PALSLOT_PLAYER,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_BIKE_TIRE,
    .oam = &gObjectEventBaseOam_32x32,
    .subspriteTables = sOamTables_32x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_VeldrisDPFMachBike,
};

const u32 gObjectEventPic_VeldrisDPFSurfing[] = INCGFX_U32("graphics/object_events/pics/people/dp_player/dawn/surfing.png", ".4bpp", "-mwidth 4 -mheight 4");

static const struct SpriteFrameImage sPicTable_VeldrisDPFSurfing[] = {
    overworld_frame(gObjectEventPic_VeldrisDPFSurfing, 4, 4, 0),
    overworld_frame(gObjectEventPic_VeldrisDPFSurfing, 4, 4, 2),
    overworld_frame(gObjectEventPic_VeldrisDPFSurfing, 4, 4, 4),
    overworld_frame(gObjectEventPic_VeldrisDPFSurfing, 4, 4, 0),
    overworld_frame(gObjectEventPic_VeldrisDPFSurfing, 4, 4, 0),
    overworld_frame(gObjectEventPic_VeldrisDPFSurfing, 4, 4, 2),
    overworld_frame(gObjectEventPic_VeldrisDPFSurfing, 4, 4, 2),
    overworld_frame(gObjectEventPic_VeldrisDPFSurfing, 4, 4, 4),
    overworld_frame(gObjectEventPic_VeldrisDPFSurfing, 4, 4, 4),
    overworld_frame(gObjectEventPic_VeldrisDPFSurfing, 4, 4, 1),
    overworld_frame(gObjectEventPic_VeldrisDPFSurfing, 4, 4, 3),
    overworld_frame(gObjectEventPic_VeldrisDPFSurfing, 4, 4, 5),
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_VeldrisDPFSurfing = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_VELDRIS_DP_F,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 512,
    .width = 32,
    .height = 32,
    .paletteSlot = PALSLOT_PLAYER,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_32x32,
    .subspriteTables = sOamTables_32x32,
    .anims = sAnimTable_Surfing,
    .images = sPicTable_VeldrisDPFSurfing,
};

const u32 gObjectEventPic_VeldrisDPFFieldMove[] = INCGFX_U32("graphics/object_events/pics/people/dp_player/dawn/field_move.png", ".4bpp", "-mwidth 4 -mheight 4");

static const struct SpriteFrameImage sPicTable_VeldrisDPFFieldMove[] = {
    overworld_ascending_frames(gObjectEventPic_VeldrisDPFFieldMove, 4, 4),
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_VeldrisDPFFieldMove = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_VELDRIS_DP_F,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_BRIDGE_REFLECTION,
    .size = 512,
    .width = 32,
    .height = 32,
    .paletteSlot = PALSLOT_PLAYER,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_32x32,
    .subspriteTables = sOamTables_32x32,
    .anims = sAnimTable_FieldMove,
    .images = sPicTable_VeldrisDPFFieldMove,
};

const u32 gObjectEventPic_VeldrisDPFFishing[] = INCGFX_U32("graphics/object_events/pics/people/dp_player/dawn/fishing.png", ".4bpp", "-mwidth 4 -mheight 4");

static const struct SpriteFrameImage sPicTable_VeldrisDPFFishing[] = {
    overworld_ascending_frames(gObjectEventPic_VeldrisDPFFishing, 4, 4),
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_VeldrisDPFFishing = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_VELDRIS_DP_F,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_BRIDGE_REFLECTION,
    .size = 512,
    .width = 32,
    .height = 32,
    .paletteSlot = PALSLOT_PLAYER,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_32x32,
    .subspriteTables = sOamTables_32x32,
    .anims = sAnimTable_Fishing,
    .images = sPicTable_VeldrisDPFFishing,
};

const u32 gObjectEventPic_VeldrisDPFWatering[] = INCGFX_U32("graphics/object_events/pics/people/dp_player/dawn/watering.png", ".4bpp", "-mwidth 4 -mheight 4");

static const struct SpriteFrameImage sPicTable_VeldrisDPFWatering[] = {
    overworld_frame(gObjectEventPic_VeldrisDPFWatering, 4, 4, 0),
    overworld_frame(gObjectEventPic_VeldrisDPFWatering, 4, 4, 2),
    overworld_frame(gObjectEventPic_VeldrisDPFWatering, 4, 4, 4),
    overworld_frame(gObjectEventPic_VeldrisDPFWatering, 4, 4, 1),
    overworld_frame(gObjectEventPic_VeldrisDPFWatering, 4, 4, 1),
    overworld_frame(gObjectEventPic_VeldrisDPFWatering, 4, 4, 3),
    overworld_frame(gObjectEventPic_VeldrisDPFWatering, 4, 4, 3),
    overworld_frame(gObjectEventPic_VeldrisDPFWatering, 4, 4, 5),
    overworld_frame(gObjectEventPic_VeldrisDPFWatering, 4, 4, 5),
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_VeldrisDPFWatering = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_VELDRIS_DP_F,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_BRIDGE_REFLECTION,
    .size = 512,
    .width = 32,
    .height = 32,
    .paletteSlot = PALSLOT_PLAYER,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_32x32,
    .subspriteTables = sOamTables_32x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_VeldrisDPFWatering,
};
