// Diamond/Pearl overworlds by spilledpizza and others (CREDITS.md). Generated by design/tools/sprites/import_dp.py.
// Each has its own palette, so keep the number of different DP people on one screen modest.

const u32 gObjectEventPic_DP_Aaron[] = INCGFX_U32("graphics/object_events/pics/people/dp/aaron.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Aaron[] = INCGFX_U16("graphics/object_events/pics/people/dp/aaron.png", ".gbapal");
const u32 gObjectEventPic_DP_AceTrainerF[] = INCGFX_U32("graphics/object_events/pics/people/dp/ace_trainer_f.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_AceTrainerF[] = INCGFX_U16("graphics/object_events/pics/people/dp/ace_trainer_f.png", ".gbapal");
const u32 gObjectEventPic_DP_AceTrainerM[] = INCGFX_U32("graphics/object_events/pics/people/dp/ace_trainer_m.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_AceTrainerM[] = INCGFX_U16("graphics/object_events/pics/people/dp/ace_trainer_m.png", ".gbapal");
const u32 gObjectEventPic_DP_AceTrainerSnowM[] = INCGFX_U32("graphics/object_events/pics/people/dp/ace_trainer_snow_m.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_AceTrainerSnowM[] = INCGFX_U16("graphics/object_events/pics/people/dp/ace_trainer_snow_m.png", ".gbapal");
const u32 gObjectEventPic_DP_Barry[] = INCGFX_U32("graphics/object_events/pics/people/dp/barry.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Barry[] = INCGFX_U16("graphics/object_events/pics/people/dp/barry.png", ".gbapal");
const u32 gObjectEventPic_DP_BattleGirl[] = INCGFX_U32("graphics/object_events/pics/people/dp/battle_girl.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_BattleGirl[] = INCGFX_U16("graphics/object_events/pics/people/dp/battle_girl.png", ".gbapal");
const u32 gObjectEventPic_DP_Beauty[] = INCGFX_U32("graphics/object_events/pics/people/dp/beauty.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Beauty[] = INCGFX_U16("graphics/object_events/pics/people/dp/beauty.png", ".gbapal");
const u32 gObjectEventPic_DP_Bertha[] = INCGFX_U32("graphics/object_events/pics/people/dp/bertha.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Bertha[] = INCGFX_U16("graphics/object_events/pics/people/dp/bertha.png", ".gbapal");
const u32 gObjectEventPic_DP_BlackBelt[] = INCGFX_U32("graphics/object_events/pics/people/dp/black_belt.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_BlackBelt[] = INCGFX_U16("graphics/object_events/pics/people/dp/black_belt.png", ".gbapal");
const u32 gObjectEventPic_DP_BreederF[] = INCGFX_U32("graphics/object_events/pics/people/dp/breeder_f.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_BreederF[] = INCGFX_U16("graphics/object_events/pics/people/dp/breeder_f.png", ".gbapal");
const u32 gObjectEventPic_DP_BugCatcher[] = INCGFX_U32("graphics/object_events/pics/people/dp/bug_catcher.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_BugCatcher[] = INCGFX_U16("graphics/object_events/pics/people/dp/bug_catcher.png", ".gbapal");
const u32 gObjectEventPic_DP_Byron[] = INCGFX_U32("graphics/object_events/pics/people/dp/byron.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Byron[] = INCGFX_U16("graphics/object_events/pics/people/dp/byron.png", ".gbapal");
const u32 gObjectEventPic_DP_Camper[] = INCGFX_U32("graphics/object_events/pics/people/dp/camper.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Camper[] = INCGFX_U16("graphics/object_events/pics/people/dp/camper.png", ".gbapal");
const u32 gObjectEventPic_DP_Charon[] = INCGFX_U32("graphics/object_events/pics/people/dp/charon.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Charon[] = INCGFX_U16("graphics/object_events/pics/people/dp/charon.png", ".gbapal");
const u32 gObjectEventPic_DP_Cheryl[] = INCGFX_U32("graphics/object_events/pics/people/dp/cheryl.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Cheryl[] = INCGFX_U16("graphics/object_events/pics/people/dp/cheryl.png", ".gbapal");
const u32 gObjectEventPic_DP_Cowgirl[] = INCGFX_U32("graphics/object_events/pics/people/dp/cowgirl.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Cowgirl[] = INCGFX_U16("graphics/object_events/pics/people/dp/cowgirl.png", ".gbapal");
const u32 gObjectEventPic_DP_CrasherWake[] = INCGFX_U32("graphics/object_events/pics/people/dp/crasher_wake.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_CrasherWake[] = INCGFX_U16("graphics/object_events/pics/people/dp/crasher_wake.png", ".gbapal");
const u32 gObjectEventPic_DP_Cynthia[] = INCGFX_U32("graphics/object_events/pics/people/dp/cynthia.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Cynthia[] = INCGFX_U16("graphics/object_events/pics/people/dp/cynthia.png", ".gbapal");
const u32 gObjectEventPic_DP_Cyrus[] = INCGFX_U32("graphics/object_events/pics/people/dp/cyrus.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Cyrus[] = INCGFX_U16("graphics/object_events/pics/people/dp/cyrus.png", ".gbapal");
const u32 gObjectEventPic_DP_DragonTamer[] = INCGFX_U32("graphics/object_events/pics/people/dp/dragon_tamer.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_DragonTamer[] = INCGFX_U16("graphics/object_events/pics/people/dp/dragon_tamer.png", ".gbapal");
const u32 gObjectEventPic_DP_Fantina[] = INCGFX_U32("graphics/object_events/pics/people/dp/fantina.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Fantina[] = INCGFX_U16("graphics/object_events/pics/people/dp/fantina.png", ".gbapal");
const u32 gObjectEventPic_DP_Fisherman[] = INCGFX_U32("graphics/object_events/pics/people/dp/fisherman.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Fisherman[] = INCGFX_U16("graphics/object_events/pics/people/dp/fisherman.png", ".gbapal");
const u32 gObjectEventPic_DP_GalacticGruntF[] = INCGFX_U32("graphics/object_events/pics/people/dp/galactic_grunt_f.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_GalacticGruntF[] = INCGFX_U16("graphics/object_events/pics/people/dp/galactic_grunt_f.png", ".gbapal");
const u32 gObjectEventPic_DP_GalacticGruntM[] = INCGFX_U32("graphics/object_events/pics/people/dp/galactic_grunt_m.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_GalacticGruntM[] = INCGFX_U16("graphics/object_events/pics/people/dp/galactic_grunt_m.png", ".gbapal");
const u32 gObjectEventPic_DP_Gentleman[] = INCGFX_U32("graphics/object_events/pics/people/dp/gentleman.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Gentleman[] = INCGFX_U16("graphics/object_events/pics/people/dp/gentleman.png", ".gbapal");
const u32 gObjectEventPic_DP_Hiker[] = INCGFX_U32("graphics/object_events/pics/people/dp/hiker.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Hiker[] = INCGFX_U16("graphics/object_events/pics/people/dp/hiker.png", ".gbapal");
const u32 gObjectEventPic_DP_Jupiter[] = INCGFX_U32("graphics/object_events/pics/people/dp/jupiter.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Jupiter[] = INCGFX_U16("graphics/object_events/pics/people/dp/jupiter.png", ".gbapal");
const u32 gObjectEventPic_DP_Lady[] = INCGFX_U32("graphics/object_events/pics/people/dp/lady.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Lady[] = INCGFX_U16("graphics/object_events/pics/people/dp/lady.png", ".gbapal");
const u32 gObjectEventPic_DP_Looker[] = INCGFX_U32("graphics/object_events/pics/people/dp/looker.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Looker[] = INCGFX_U16("graphics/object_events/pics/people/dp/looker.png", ".gbapal");
const u32 gObjectEventPic_DP_Lucian[] = INCGFX_U32("graphics/object_events/pics/people/dp/lucian.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Lucian[] = INCGFX_U16("graphics/object_events/pics/people/dp/lucian.png", ".gbapal");
const u32 gObjectEventPic_DP_Marley[] = INCGFX_U32("graphics/object_events/pics/people/dp/marley.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Marley[] = INCGFX_U16("graphics/object_events/pics/people/dp/marley.png", ".gbapal");
const u32 gObjectEventPic_DP_Mars[] = INCGFX_U32("graphics/object_events/pics/people/dp/mars.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Mars[] = INCGFX_U16("graphics/object_events/pics/people/dp/mars.png", ".gbapal");
const u32 gObjectEventPic_DP_Maylene[] = INCGFX_U32("graphics/object_events/pics/people/dp/maylene.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Maylene[] = INCGFX_U16("graphics/object_events/pics/people/dp/maylene.png", ".gbapal");
const u32 gObjectEventPic_DP_Mira[] = INCGFX_U32("graphics/object_events/pics/people/dp/mira.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Mira[] = INCGFX_U16("graphics/object_events/pics/people/dp/mira.png", ".gbapal");
const u32 gObjectEventPic_DP_Officer[] = INCGFX_U32("graphics/object_events/pics/people/dp/officer.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Officer[] = INCGFX_U16("graphics/object_events/pics/people/dp/officer.png", ".gbapal");
const u32 gObjectEventPic_DP_Painter[] = INCGFX_U32("graphics/object_events/pics/people/dp/painter.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Painter[] = INCGFX_U16("graphics/object_events/pics/people/dp/painter.png", ".gbapal");
const u32 gObjectEventPic_DP_Palmer[] = INCGFX_U32("graphics/object_events/pics/people/dp/palmer.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Palmer[] = INCGFX_U16("graphics/object_events/pics/people/dp/palmer.png", ".gbapal");
const u32 gObjectEventPic_DP_ParasolLady[] = INCGFX_U32("graphics/object_events/pics/people/dp/parasol_lady.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_ParasolLady[] = INCGFX_U16("graphics/object_events/pics/people/dp/parasol_lady.png", ".gbapal");
const u32 gObjectEventPic_DP_Picnicker[] = INCGFX_U32("graphics/object_events/pics/people/dp/picnicker.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Picnicker[] = INCGFX_U16("graphics/object_events/pics/people/dp/picnicker.png", ".gbapal");
const u32 gObjectEventPic_DP_PokeKid[] = INCGFX_U32("graphics/object_events/pics/people/dp/poke_kid.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_PokeKid[] = INCGFX_U16("graphics/object_events/pics/people/dp/poke_kid.png", ".gbapal");
const u32 gObjectEventPic_DP_PokeRangerF[] = INCGFX_U32("graphics/object_events/pics/people/dp/poke_ranger_f.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_PokeRangerF[] = INCGFX_U16("graphics/object_events/pics/people/dp/poke_ranger_f.png", ".gbapal");
const u32 gObjectEventPic_DP_PokeRangerM[] = INCGFX_U32("graphics/object_events/pics/people/dp/poke_ranger_m.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_PokeRangerM[] = INCGFX_U16("graphics/object_events/pics/people/dp/poke_ranger_m.png", ".gbapal");
const u32 gObjectEventPic_DP_PokefanF[] = INCGFX_U32("graphics/object_events/pics/people/dp/pokefan_f.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_PokefanF[] = INCGFX_U16("graphics/object_events/pics/people/dp/pokefan_f.png", ".gbapal");
const u32 gObjectEventPic_DP_PokefanM[] = INCGFX_U32("graphics/object_events/pics/people/dp/pokefan_m.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_PokefanM[] = INCGFX_U16("graphics/object_events/pics/people/dp/pokefan_m.png", ".gbapal");
const u32 gObjectEventPic_DP_ProfRowan[] = INCGFX_U32("graphics/object_events/pics/people/dp/prof_rowan.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_ProfRowan[] = INCGFX_U16("graphics/object_events/pics/people/dp/prof_rowan.png", ".gbapal");
const u32 gObjectEventPic_DP_PsychicM[] = INCGFX_U32("graphics/object_events/pics/people/dp/psychic_m.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_PsychicM[] = INCGFX_U16("graphics/object_events/pics/people/dp/psychic_m.png", ".gbapal");
const u32 gObjectEventPic_DP_Rancher[] = INCGFX_U32("graphics/object_events/pics/people/dp/rancher.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Rancher[] = INCGFX_U16("graphics/object_events/pics/people/dp/rancher.png", ".gbapal");
const u32 gObjectEventPic_DP_RichBoy[] = INCGFX_U32("graphics/object_events/pics/people/dp/rich_boy.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_RichBoy[] = INCGFX_U16("graphics/object_events/pics/people/dp/rich_boy.png", ".gbapal");
const u32 gObjectEventPic_DP_RichLady[] = INCGFX_U32("graphics/object_events/pics/people/dp/rich_lady.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_RichLady[] = INCGFX_U16("graphics/object_events/pics/people/dp/rich_lady.png", ".gbapal");
const u32 gObjectEventPic_DP_Rocker[] = INCGFX_U32("graphics/object_events/pics/people/dp/rocker.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Rocker[] = INCGFX_U16("graphics/object_events/pics/people/dp/rocker.png", ".gbapal");
const u32 gObjectEventPic_DP_Roughneck[] = INCGFX_U32("graphics/object_events/pics/people/dp/roughneck.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Roughneck[] = INCGFX_U16("graphics/object_events/pics/people/dp/roughneck.png", ".gbapal");
const u32 gObjectEventPic_DP_RuinManiac[] = INCGFX_U32("graphics/object_events/pics/people/dp/ruin_maniac.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_RuinManiac[] = INCGFX_U16("graphics/object_events/pics/people/dp/ruin_maniac.png", ".gbapal");
const u32 gObjectEventPic_DP_Sailor[] = INCGFX_U32("graphics/object_events/pics/people/dp/sailor.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Sailor[] = INCGFX_U16("graphics/object_events/pics/people/dp/sailor.png", ".gbapal");
const u32 gObjectEventPic_DP_Saturn[] = INCGFX_U32("graphics/object_events/pics/people/dp/saturn.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Saturn[] = INCGFX_U16("graphics/object_events/pics/people/dp/saturn.png", ".gbapal");
const u32 gObjectEventPic_DP_Scientist[] = INCGFX_U32("graphics/object_events/pics/people/dp/scientist.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Scientist[] = INCGFX_U16("graphics/object_events/pics/people/dp/scientist.png", ".gbapal");
const u32 gObjectEventPic_DP_SkierF[] = INCGFX_U32("graphics/object_events/pics/people/dp/skier_f.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_SkierF[] = INCGFX_U16("graphics/object_events/pics/people/dp/skier_f.png", ".gbapal");
const u32 gObjectEventPic_DP_SkierM[] = INCGFX_U32("graphics/object_events/pics/people/dp/skier_m.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_SkierM[] = INCGFX_U16("graphics/object_events/pics/people/dp/skier_m.png", ".gbapal");
const u32 gObjectEventPic_DP_Socialite[] = INCGFX_U32("graphics/object_events/pics/people/dp/socialite.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Socialite[] = INCGFX_U16("graphics/object_events/pics/people/dp/socialite.png", ".gbapal");
const u32 gObjectEventPic_DP_Supernerd[] = INCGFX_U32("graphics/object_events/pics/people/dp/supernerd.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Supernerd[] = INCGFX_U16("graphics/object_events/pics/people/dp/supernerd.png", ".gbapal");
const u32 gObjectEventPic_DP_SwimmerF[] = INCGFX_U32("graphics/object_events/pics/people/dp/swimmer_f.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_SwimmerF[] = INCGFX_U16("graphics/object_events/pics/people/dp/swimmer_f.png", ".gbapal");
const u32 gObjectEventPic_DP_SwimmerF2[] = INCGFX_U32("graphics/object_events/pics/people/dp/swimmer_f2.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_SwimmerF2[] = INCGFX_U16("graphics/object_events/pics/people/dp/swimmer_f2.png", ".gbapal");
const u32 gObjectEventPic_DP_SwimmerM[] = INCGFX_U32("graphics/object_events/pics/people/dp/swimmer_m.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_SwimmerM[] = INCGFX_U16("graphics/object_events/pics/people/dp/swimmer_m.png", ".gbapal");
const u32 gObjectEventPic_DP_SwimmerM2[] = INCGFX_U32("graphics/object_events/pics/people/dp/swimmer_m2.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_SwimmerM2[] = INCGFX_U16("graphics/object_events/pics/people/dp/swimmer_m2.png", ".gbapal");
const u32 gObjectEventPic_DP_Volkner[] = INCGFX_U32("graphics/object_events/pics/people/dp/volkner.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Volkner[] = INCGFX_U16("graphics/object_events/pics/people/dp/volkner.png", ".gbapal");
const u32 gObjectEventPic_DP_Waiter[] = INCGFX_U32("graphics/object_events/pics/people/dp/waiter.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Waiter[] = INCGFX_U16("graphics/object_events/pics/people/dp/waiter.png", ".gbapal");
const u32 gObjectEventPic_DP_Waitress[] = INCGFX_U32("graphics/object_events/pics/people/dp/waitress.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Waitress[] = INCGFX_U16("graphics/object_events/pics/people/dp/waitress.png", ".gbapal");
const u32 gObjectEventPic_DP_Worker[] = INCGFX_U32("graphics/object_events/pics/people/dp/worker.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Worker[] = INCGFX_U16("graphics/object_events/pics/people/dp/worker.png", ".gbapal");
const u32 gObjectEventPic_DP_YoungCoupleF[] = INCGFX_U32("graphics/object_events/pics/people/dp/young_couple_f.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_YoungCoupleF[] = INCGFX_U16("graphics/object_events/pics/people/dp/young_couple_f.png", ".gbapal");
const u32 gObjectEventPic_DP_YoungCoupleM[] = INCGFX_U32("graphics/object_events/pics/people/dp/young_couple_m.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_YoungCoupleM[] = INCGFX_U16("graphics/object_events/pics/people/dp/young_couple_m.png", ".gbapal");
const u32 gObjectEventPic_DP_Youngster[] = INCGFX_U32("graphics/object_events/pics/people/dp/youngster.png", ".4bpp", "-mwidth 2 -mheight 4");
const u16 gObjectEventPal_DP_Youngster[] = INCGFX_U16("graphics/object_events/pics/people/dp/youngster.png", ".gbapal");

static const struct SpriteFrameImage sPicTable_DP_Aaron[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Aaron, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_AceTrainerF[] = {
    overworld_ascending_frames(gObjectEventPic_DP_AceTrainerF, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_AceTrainerM[] = {
    overworld_ascending_frames(gObjectEventPic_DP_AceTrainerM, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_AceTrainerSnowM[] = {
    overworld_ascending_frames(gObjectEventPic_DP_AceTrainerSnowM, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Barry[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Barry, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_BattleGirl[] = {
    overworld_ascending_frames(gObjectEventPic_DP_BattleGirl, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Beauty[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Beauty, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Bertha[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Bertha, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_BlackBelt[] = {
    overworld_ascending_frames(gObjectEventPic_DP_BlackBelt, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_BreederF[] = {
    overworld_ascending_frames(gObjectEventPic_DP_BreederF, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_BugCatcher[] = {
    overworld_ascending_frames(gObjectEventPic_DP_BugCatcher, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Byron[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Byron, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Camper[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Camper, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Charon[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Charon, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Cheryl[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Cheryl, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Cowgirl[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Cowgirl, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_CrasherWake[] = {
    overworld_ascending_frames(gObjectEventPic_DP_CrasherWake, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Cynthia[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Cynthia, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Cyrus[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Cyrus, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_DragonTamer[] = {
    overworld_ascending_frames(gObjectEventPic_DP_DragonTamer, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Fantina[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Fantina, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Fisherman[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Fisherman, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_GalacticGruntF[] = {
    overworld_ascending_frames(gObjectEventPic_DP_GalacticGruntF, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_GalacticGruntM[] = {
    overworld_ascending_frames(gObjectEventPic_DP_GalacticGruntM, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Gentleman[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Gentleman, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Hiker[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Hiker, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Jupiter[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Jupiter, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Lady[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Lady, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Looker[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Looker, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Lucian[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Lucian, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Marley[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Marley, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Mars[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Mars, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Maylene[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Maylene, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Mira[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Mira, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Officer[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Officer, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Painter[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Painter, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Palmer[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Palmer, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_ParasolLady[] = {
    overworld_ascending_frames(gObjectEventPic_DP_ParasolLady, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Picnicker[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Picnicker, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_PokeKid[] = {
    overworld_ascending_frames(gObjectEventPic_DP_PokeKid, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_PokeRangerF[] = {
    overworld_ascending_frames(gObjectEventPic_DP_PokeRangerF, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_PokeRangerM[] = {
    overworld_ascending_frames(gObjectEventPic_DP_PokeRangerM, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_PokefanF[] = {
    overworld_ascending_frames(gObjectEventPic_DP_PokefanF, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_PokefanM[] = {
    overworld_ascending_frames(gObjectEventPic_DP_PokefanM, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_ProfRowan[] = {
    overworld_ascending_frames(gObjectEventPic_DP_ProfRowan, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_PsychicM[] = {
    overworld_ascending_frames(gObjectEventPic_DP_PsychicM, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Rancher[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Rancher, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_RichBoy[] = {
    overworld_ascending_frames(gObjectEventPic_DP_RichBoy, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_RichLady[] = {
    overworld_ascending_frames(gObjectEventPic_DP_RichLady, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Rocker[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Rocker, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Roughneck[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Roughneck, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_RuinManiac[] = {
    overworld_ascending_frames(gObjectEventPic_DP_RuinManiac, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Sailor[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Sailor, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Saturn[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Saturn, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Scientist[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Scientist, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_SkierF[] = {
    overworld_ascending_frames(gObjectEventPic_DP_SkierF, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_SkierM[] = {
    overworld_ascending_frames(gObjectEventPic_DP_SkierM, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Socialite[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Socialite, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Supernerd[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Supernerd, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_SwimmerF[] = {
    overworld_ascending_frames(gObjectEventPic_DP_SwimmerF, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_SwimmerF2[] = {
    overworld_ascending_frames(gObjectEventPic_DP_SwimmerF2, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_SwimmerM[] = {
    overworld_ascending_frames(gObjectEventPic_DP_SwimmerM, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_SwimmerM2[] = {
    overworld_ascending_frames(gObjectEventPic_DP_SwimmerM2, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Volkner[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Volkner, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Waiter[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Waiter, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Waitress[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Waitress, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Worker[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Worker, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_YoungCoupleF[] = {
    overworld_ascending_frames(gObjectEventPic_DP_YoungCoupleF, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_YoungCoupleM[] = {
    overworld_ascending_frames(gObjectEventPic_DP_YoungCoupleM, 2, 4),
};

static const struct SpriteFrameImage sPicTable_DP_Youngster[] = {
    overworld_ascending_frames(gObjectEventPic_DP_Youngster, 2, 4),
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Aaron = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_AARON,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Aaron,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_AceTrainerF = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_ACE_TRAINER_F,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_AceTrainerF,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_AceTrainerM = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_ACE_TRAINER_M,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_AceTrainerM,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_AceTrainerSnowM = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_ACE_TRAINER_SNOW_M,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_AceTrainerSnowM,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Barry = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_BARRY,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Barry,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_BattleGirl = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_BATTLE_GIRL,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_BattleGirl,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Beauty = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_BEAUTY,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Beauty,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Bertha = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_BERTHA,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Bertha,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_BlackBelt = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_BLACK_BELT,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_BlackBelt,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_BreederF = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_BREEDER_F,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_BreederF,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_BugCatcher = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_BUG_CATCHER,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_BugCatcher,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Byron = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_BYRON,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Byron,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Camper = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_CAMPER,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Camper,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Charon = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_CHARON,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Charon,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Cheryl = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_CHERYL,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Cheryl,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Cowgirl = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_COWGIRL,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Cowgirl,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_CrasherWake = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_CRASHER_WAKE,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_CrasherWake,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Cynthia = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_CYNTHIA,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Cynthia,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Cyrus = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_CYRUS,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Cyrus,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_DragonTamer = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_DRAGON_TAMER,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_DragonTamer,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Fantina = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_FANTINA,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Fantina,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Fisherman = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_FISHERMAN,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Fisherman,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_GalacticGruntF = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_GALACTIC_GRUNT_F,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_GalacticGruntF,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_GalacticGruntM = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_GALACTIC_GRUNT_M,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_GalacticGruntM,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Gentleman = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_GENTLEMAN,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Gentleman,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Hiker = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_HIKER,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Hiker,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Jupiter = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_JUPITER,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Jupiter,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Lady = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_LADY,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Lady,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Looker = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_LOOKER,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Looker,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Lucian = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_LUCIAN,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Lucian,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Marley = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_MARLEY,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Marley,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Mars = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_MARS,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Mars,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Maylene = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_MAYLENE,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Maylene,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Mira = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_MIRA,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Mira,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Officer = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_OFFICER,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Officer,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Painter = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_PAINTER,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Painter,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Palmer = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_PALMER,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Palmer,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_ParasolLady = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_PARASOL_LADY,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_ParasolLady,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Picnicker = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_PICNICKER,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Picnicker,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_PokeKid = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_POKE_KID,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_PokeKid,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_PokeRangerF = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_POKE_RANGER_F,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_PokeRangerF,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_PokeRangerM = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_POKE_RANGER_M,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_PokeRangerM,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_PokefanF = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_POKEFAN_F,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_PokefanF,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_PokefanM = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_POKEFAN_M,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_PokefanM,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_ProfRowan = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_PROF_ROWAN,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_ProfRowan,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_PsychicM = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_PSYCHIC_M,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_PsychicM,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Rancher = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_RANCHER,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Rancher,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_RichBoy = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_RICH_BOY,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_RichBoy,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_RichLady = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_RICH_LADY,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_RichLady,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Rocker = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_ROCKER,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Rocker,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Roughneck = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_ROUGHNECK,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Roughneck,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_RuinManiac = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_RUIN_MANIAC,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_RuinManiac,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Sailor = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_SAILOR,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Sailor,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Saturn = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_SATURN,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Saturn,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Scientist = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_SCIENTIST,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Scientist,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_SkierF = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_SKIER_F,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_SkierF,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_SkierM = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_SKIER_M,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_SkierM,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Socialite = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_SOCIALITE,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Socialite,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Supernerd = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_SUPERNERD,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Supernerd,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_SwimmerF = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_SWIMMER_F,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_SwimmerF,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_SwimmerF2 = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_SWIMMER_F2,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_SwimmerF2,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_SwimmerM = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_SWIMMER_M,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_SwimmerM,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_SwimmerM2 = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_SWIMMER_M2,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_SwimmerM2,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Volkner = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_VOLKNER,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Volkner,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Waiter = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_WAITER,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Waiter,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Waitress = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_WAITRESS,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Waitress,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Worker = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_WORKER,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Worker,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_YoungCoupleF = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_YOUNG_COUPLE_F,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_YoungCoupleF,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_YoungCoupleM = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_YOUNG_COUPLE_M,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_YoungCoupleM,
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DP_Youngster = {
    .tileTag = TAG_NONE,
    .paletteTag = OBJ_EVENT_PAL_TAG_DP_YOUNGSTER,
    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 256,
    .width = 16,
    .height = 32,
    .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .compressed = FALSE,
    .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x32,
    .subspriteTables = sOamTables_16x32,
    .anims = sAnimTable_Standard,
    .images = sPicTable_DP_Youngster,
};

